
typedef signed char        __int8_t;
typedef unsigned char      __uint8_t;
typedef short int          __int16_t;
typedef short unsigned int __uint16_t;
typedef int                __int32_t;
typedef unsigned int       __uint32_t;
typedef long int           __int64_t;
typedef long unsigned int  __uint64_t;
typedef signed char        __int_least8_t;
typedef unsigned char      __uint_least8_t;
typedef short int          __int_least16_t;
typedef short unsigned int __uint_least16_t;
typedef int                __int_least32_t;
typedef unsigned int       __uint_least32_t;
typedef long int           __int_least64_t;
typedef long unsigned int  __uint_least64_t;
typedef long int           __intmax_t;
typedef long unsigned int  __uintmax_t;
typedef long int           __intptr_t;
typedef long unsigned int  __uintptr_t;
typedef long int           ptrdiff_t;
typedef long unsigned int  size_t;
typedef int                wchar_t;
typedef struct
{
    long long   __max_align_ll __attribute__((__aligned__(__alignof__(long long))));
    long double __max_align_ld __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
struct __locale_t;
typedef struct __locale_t* locale_t;
int                        isalnum(int __c);
int                        isalpha(int __c);
int                        iscntrl(int __c);
int                        isdigit(int __c);
int                        isgraph(int __c);
int                        islower(int __c);
int                        isprint(int __c);
int                        ispunct(int __c);
int                        isspace(int __c);
int                        isupper(int __c);
int                        isxdigit(int __c);
int                        tolower(int __c);
int                        toupper(int __c);
int                        isblank(int __c);
int                        isascii(int __c);
int                        toascii(int __c);
extern int                 isalnum_l(int __c, locale_t __l);
extern int                 isalpha_l(int __c, locale_t __l);
extern int                 isblank_l(int __c, locale_t __l);
extern int                 iscntrl_l(int __c, locale_t __l);
extern int                 isdigit_l(int __c, locale_t __l);
extern int                 isgraph_l(int __c, locale_t __l);
extern int                 islower_l(int __c, locale_t __l);
extern int                 isprint_l(int __c, locale_t __l);
extern int                 ispunct_l(int __c, locale_t __l);
extern int                 isspace_l(int __c, locale_t __l);
extern int                 isupper_l(int __c, locale_t __l);
extern int                 isxdigit_l(int __c, locale_t __l);
extern int                 tolower_l(int __c, locale_t __l);
extern int                 toupper_l(int __c, locale_t __l);
extern int                 isascii_l(int __c, locale_t __l);
extern int                 toascii_l(int __c, locale_t __l);
extern const char          _ctype_[];
int                        isblank(int c) { return (((_ctype_)[c + 1] & 0200) || (c == '\t')); }
